FinanceBudget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('budget.urls')),
]

budget/urls.py
from django.urls import path, include

from .views import index, OperationListView, OperationUpdate, FamilyChartView, \
    delete_category, get_data_for_chart, delete_operation, ChartView, FamilyView, CategoryCreateView, \
    get_category_by_ajax, delete_user_from_family, DeleteFamilyView, family_operation_view, OperationCreate, \
    OperationView, get_operation_by_ajax, get_data_for_chart_family_by_ajax

urlpatterns = [
    path('ajax/family/operations/', get_data_for_chart_family_by_ajax),
    path('ajax/operations/', get_operation_by_ajax),
    path('ajax/<int:pk>/delete/', delete_category, name='b-ajax-delete-category'),
    path('ajax/chart/', get_data_for_chart),
    path('ajax/category/', get_category_by_ajax),

    path('operation/js/', OperationView.as_view()),
    path('operation/chart/', ChartView.as_view(), name='b-chart'),
    path('operation/add/', OperationCreate.as_view(), name='b-operation-create'),
    path('operation/<int:pk>/delete/', delete_operation, name='b-operation-delete'),  # is_ajax
    path('operation/<int:pk>/', OperationUpdate.as_view(), name='b-operation-update'),
    path('operation/', OperationListView.as_view(), name='b-list-operation'),

    path('category/', CategoryCreateView.as_view(), name='b-category'),
    path('category/<int:pk>/delete/', delete_category, name='b-category-delete'),

    path('family/user/<int:pk>/remove/', delete_user_from_family, name='b-family-delete-user'),
    path('family/operation/', family_operation_view, name='b-family-operation'),
    path('family/delete/', DeleteFamilyView.as_view(), name='b-family-delete'),
    path('family/chart/', FamilyChartView.as_view(), name='b-family-chart'),
    path('family/', FamilyView.as_view(), name='b-family'),

    path('', index, name='b-index'),
]

budget/models.py
from django.db import models
from django.contrib.auth.models import User

from uuid import uuid4


# Create your models here.

def get_system_category(type_pay):
    return Category.objects.get_or_create(type_pay=type_pay, name='Прочее', user_id=None)[0].id


class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name="Категория")
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    type_pay = models.PositiveSmallIntegerField(choices=((0, 'Расход'), (1, 'Доход')), default=0)

    def __str__(self):
        return self.name  # + " | " + self.get_type_pay_display()

    def delete(self, using=None, keep_parents=False):
        Operation.objects.filter(category_id=self.id).update(category_id=get_system_category(self.type_pay))
        return super().delete(using=None, keep_parents=False)


class Operation(models.Model):
    value = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Сумма")
    date = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=128, verbose_name="Описание", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория",
                                 related_name='operations', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='operations')

    def __str__(self):
        return f'{self.value} | {self.category} | {self.date} | {self.user}'

    # class Meta:
    # ordering = ['-date', '-id']


class Family(models.Model):
    name = models.CharField(max_length=32, verbose_name="Семья")
    author = models.ForeignKey(User, verbose_name='Создатель', blank=True, null=True, on_delete=models.CASCADE,
                               related_name='author_families')
    uuid = models.UUIDField(default=uuid4, editable=True)
    users = models.ManyToManyField(User, blank=True, related_name='family')
    # users = models.ManyToManyField(User, through='FamilyUsers', through_fields=('family', 'user'),
    #                                related_name='family')

    def __str__(self):
        return self.name

    # class Meta:
    #     unique_together = ['users__family', 'users__user']


# class FamilyUsers(models.Model):
#     family = models.ForeignKey(Family, on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#
#     class Meta:
#         db_table = 'budget_family_users'
#         unique_together = ['family', 'user']

budget/forms.py
from django import forms
from django.forms import ValidationError
from django.contrib.auth.models import User

from unidecode import unidecode

from .models import Operation, Category, Family


class FamilyForm(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['name']


class OperationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in ['value', 'description', 'category']:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'placeholder': self.fields[field].label})
        self.fields['value'].widget.attrs.update({'min': 0})
        self.fields['description'].widget.attrs.update({'list': 'desc-list'})

    class Meta:
        model = Operation
        fields = ['value', 'description', 'category']

    def clean_value(self):
        value = self.cleaned_data['value']
        if value < 0 or value == 0:
            raise ValidationError("Введено некорректное значение")
        return value


class CategoryForm(forms.ModelForm):
    user_id = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in ['name', 'type_pay']:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'placeholder': self.fields[field].label})

    class Meta:
        model = Category
        fields = ['name', 'type_pay', 'user_id']

    def clean(self):
        user_id = self.cleaned_data['user_id']
        name = self.cleaned_data['name']
        type_pay = self.cleaned_data['type_pay']

        if Category.objects.filter(user_id=user_id, name=name, type_pay=type_pay).exists():
            raise ValidationError({'name': 'Категория уже существует'})
        return self.cleaned_data

budget/views.py
import datetime, time, re
from pprint import pprint

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse, Http404
from django.views.generic import UpdateView, CreateView, View, TemplateView

from django.db.models import Q, Sum, F
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.dates import MonthArchiveView
from django.core.exceptions import PermissionDenied
from django.db.models import Sum, Count

from django.contrib.auth.models import User

from .forms import OperationForm, CategoryForm, FamilyForm
from .models import Category, Operation, Family

colors = [
    ['#A35EEB', '#EBB76A', '#525AEB', '#EAEB3B', '#46A5EB'],
    ['#0E966D', '#1CC40A', '#CCC900', '#E3A40B', '#D9550B'],
]


# Create your views here.
def get_category_by_ajax(request):
    """Получение категорий по ajax"""
    if request.user.is_anonymous:
        raise PermissionDenied
    if request.is_ajax():
        type_pay = request.GET.get('type_pay', 0)
        categories = list(
            Category.objects.filter((Q(user_id=None) | Q(user_id=request.user.id)) &
                                    Q(type_pay=type_pay)).values('id', 'name').order_by('name'))
        return JsonResponse({'categories': categories}, status=200)


def get_operation_by_ajax(request):
    if request.user.is_anonymous:
        raise PermissionDenied

    date_str_format = request.GET.get('month', datetime.datetime.now().strftime('%Y-%m'))
    year, month = map(int, date_str_format.split('-'))

    operations = Operation.objects.filter(user_id=request.user.id,
                                          date__month=month,
                                          date__year=year)

    total = operations.filter(category__type_pay=1).aggregate(total=Sum('value'))['total']
    total_cost = operations.filter(category__type_pay=0).aggregate(total=Sum('value'))['total']
    if total is None:
        total = 0
    if total_cost is None:
        total_cost = 0
    total -= total_cost

    operations = operations.values('id', 'value', 'description',
                                   'category__type_pay',
                                   'category__name', 'date').order_by('-date', '-id')
    return JsonResponse({'operations': list(operations), 'total': total})


def get_data_for_chart_family_by_ajax(request):
    """Получение данных для построения диаграммы. ajax"""
    if request.user.is_anonymous:
        raise PermissionDenied

    type_pay = int(request.GET.get('type_pay', 0))
    year = int(request.GET.get('year', datetime.datetime.now().year))
    month = int(request.GET.get('month', -1))

    family = Family.objects.get(users=request.user.id)
    data = Operation.objects.filter(category__type_pay=type_pay,
                                    user__in=family.users.all())
    if month == -1:
        data = data.filter(date__year=year)
    else:
        data = data.filter(date__year=year, date__month=month)

    categories = data.values(_category=F('category__name')).annotate(total=Sum('value'))
    categories = list(categories)

    users = data.values(_user=F('user__username')).annotate(total=Sum('value'))
    users = list(users)

    for i in range(len(categories)):
        item = categories[i]
        item.update({'color': colors[type_pay][i % len(colors[type_pay])]})

    for i in range(len(users)):
        item = users[i]
        item.update({'color': colors[type_pay][i % len(colors[type_pay])]})

    return JsonResponse({'categories': categories, 'users': users}, status=200)


class OperationView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('a-login')
    template_name = 'budget/list_operation_js.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.filter(Q(user_id=None) | Q(user_id=self.request.user.id)).values('id', 'name')
        context.update({'categories': categories})
        return context


# def family_view(request):
#     if request.user.is_anonymous:
#         return redirect('/')
#
#     if request.method == 'POST':
#         uuid = request.POST.get('uuid', None)
#         if uuid and re.match(r'[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}', uuid) is not None:
#             family = Family.objects.get(uuid=uuid)
#             family.users.add(request.user)
#             return redirect('b-family')
#         form = FamilyForm(request.POST)
#         if form.is_valid():
#             form.instance.author = request.user
#             form.save()
#             form.instance.users.add(request.user)
#             return redirect('b-family')
#
#     families = Family.objects.filter(users=request.user)
#     context = {
#         'family': families[0] if families else None,
#     }
#
#     return render(request, 'budget/family.html', context=context)


class FamilyView(LoginRequiredMixin, View):
    login_url = reverse_lazy('a-login')

    def post(self, request):
        uuid = request.POST.get('uuid', None)
        if uuid and re.match(r'[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}', uuid) is not None:
            family = Family.objects.get(uuid=uuid)
            family.users.add(request.user)
            return redirect('b-family')
        form = FamilyForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            form.instance.users.add(request.user)
            return redirect('b-family')
        return redirect('b-family')

    def get(self, request):
        families = Family.objects.filter(users=request.user)
        context = {
            'family': families[0] if families else None,
        }
        return render(request, 'budget/family.html', context=context)


def family_operation_view(request):
    if request.user.is_anonymous:
        return redirect('a-login')

    family = Family.objects.filter(users=request.user)
    if family.exists():
        family = family[0]
    else:
        return redirect('b-family')

    year = int(request.GET.get('year', datetime.datetime.now().year))
    month = int(request.GET.get('month', datetime.datetime.now().month))

    operations = Operation.objects.filter(user__in=family.users.all(),
                                          date__month=month,
                                          date__year=year).order_by('-date', '-id')
    total = operations.filter(category__type_pay=1).aggregate(total=Sum('value'))['total']
    total_cost = operations.filter(category__type_pay=0).aggregate(total=Sum('value'))['total']
    if total is None:
        total = 0
    if total_cost is None:
        total_cost = 0
    total -= total_cost

    context = {
        'family': family,
        'operations': operations,
        'total': total,
        'year': year,
        'month': str(month).zfill(2),
    }
    return render(request, 'budget/family_operation.html', context=context)


def delete_user_from_family(request, pk):
    user = User.objects.get(id=pk)
    family = Family.objects.get(users=user)
    if family.author == request.user or user == request.user:
        family.users.remove(user)
    return redirect('b-family')


# def delete_family(request):
#     family = Family.objects.get(author=request.user)
#     family.delete()
#     return redirect('b-family')


class DeleteFamilyView(LoginRequiredMixin, View):
    login_url = reverse_lazy('a-login')

    def get(self, request):
        family = Family.objects.get(author=request.user)
        family.delete()
        return redirect('b-family')


def get_data_for_chart(request):
    """Получение данных для построения диаграммы. ajax"""
    if request.user.is_anonymous:
        raise PermissionDenied

    type_pay = int(request.GET.get('type_pay', 0))
    year = int(request.GET.get('year', datetime.datetime.now().year))
    month = int(request.GET.get('month', -1))

    data = Operation.objects.values('category__name').filter(category__type_pay=type_pay,
                                                             user__id=request.user.id)
    # .annotate(total=(Sum('value')))
    if month == -1:
        data = data.filter(date__year=year)
    else:
        data = data.filter(date__year=year, date__month=month)
    data = data.annotate(total=(Sum('value')))
    data = list(data)

    for i in range(len(data)):
        item = data[i]
        item.update({'color': colors[type_pay][i % len(colors[type_pay])]})

    return JsonResponse({'data': data}, status=200)


# def view_chart(request):
#     """Отображание страницы с пустой диаграммой"""
#     return render(request, 'budget/chart.html')


class ChartView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('a-login')
    template_name = 'budget/chart.html'


class FamilyChartView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('a-login')
    template_name = 'budget/chart_family.html'

    def get(self, request):
        if not Family.objects.filter(users=request.user).exists():
            return redirect('b-family')
        return super().get(request)


def delete_category(request, pk):
    """Удаление категории. Вызов происходит при помощи ajax"""
    if request.user.is_anonymous:
        raise PermissionDenied
    category = Category.objects.get(id=pk)
    if category is not None:
        if category.user == request.user:
            category.delete()
            return JsonResponse({'result': 'ok'}, status=200)
        return JsonResponse({'result': 'bad'}, status=200)


def delete_operation(request, pk):
    """Удаление операции. Вызов происходит при помощи ajax"""
    if request.user.is_anonymous:
        raise PermissionDenied
    operation = Operation.objects.get(id=pk)
    if operation is not None:
        if operation.user == request.user:
            operation.delete()
            return JsonResponse({'result': 'ok'}, status=200)

budget/templates/budget/base_operation_include.html
<ul class="nav nav-tabs">
    {% url 'b-list-operation' as operation_url %}
    {% url 'b-chart' as chart_url %}
    {% url 'b-category' as category_url %}
    <li class="nav-item">
        <a class="nav-link {% if request.path == operation_url %}active{% endif %}" href="{{operation_url}}">Расходы / Доходы</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if request.path == chart_url %}active{% endif %}" href="{{chart_url}}">Графическая сводка</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if request.path == category_url %}active{% endif %}" href="{{category_url}}">Категории</a>
    </li>
</ul>

budget/templates/budget/category.html
{% extends 'base.html' %}

{% block title %}Мои категории | {{block.super}}{% endblock title %}

{% block content %}

{% include 'budget/include/operation_tabs.html' %}

<div class="container row mt-3" id="app_category">
    <div class="col-9 col-md-3 ml-md-auto mb-2">
        <h4>Мои категории</h4>
        <ul class="list-group">
            {% for category in category_list %}
            <a href="#!"
               class="list-group-item list-group-item-action {% if category.type_pay%}text-success{%else%}text-danger{%endif%}">{{category}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"
                        v-on:click="delete_category({{category.id}}, '{{category.name}}')">
                    <span aria-hidden="true">&times;</span>
                </button>
            </a>
            {% empty %}
                <p class="text-muted">У Вас нет категорий</p>
            {% endfor %}
        </ul>
    </div>
    <div class="col-9 col-md-6 mr-md-auto  v-divider">
        <h4>Добавить новую категорию</h4>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-1">{{field}}</div>
            {% endfor %}

            {% for error in form.errors.values %}
            {{error}}
            {% endfor %}
            {{form.non_field_errors}}
            <input type="submit" value="Сохранить" class="btn btn-success btn-block">
        </form>
    </div>


</div>
{% endblock content %}

budget/templates/budget/chart.html
{% extends 'base.html' %}

{% block title %}Графическая сводка | {{block.super}}{% endblock title %}

{% block content %}

{% include 'budget/include/operation_tabs.html' %}

<div id="app-statistic">
    <div class="mt-3">
        <div class="btn-group btn-group-toggle mb-1" data-toggle="buttons">
            <label class="btn btn-outline-success active">
                <input type="radio" value="0" name="type_pay" id="type_pay_0" v-model="state_radio"
                       v-on:change="radio_changed"
                > Расход
            </label>
            <label class="btn btn-outline-success">
                <input type="radio" value="1" name="type_pay" id="type_pay_1" v-model="state_radio"
                       v-on:change="radio_changed"
                > Доход
            </label>
        </div>

        <div class="btn-group btn-group-toggle mb-1" data-toggle="buttons">
            <label class="btn btn-outline-success active">
                <input type="radio" value="0" name="type_date" id="type_date_0" v-model="state_calendar"
                       v-on:change="type_date_changed">Месяц
            </label>
            <label class="btn btn-outline-success">
                <input type="radio" value="1" name="type_date" id="type_date_1" v-model="state_calendar"
                       v-on:change="type_date_changed">Год
            </label>
        </div>

        <div class="mt-1">
            <input v-if="state_calendar==1"
                   type="number"
                   min="1970"
                   max="2100"
                   v-model='calendar_date'
                   class="form-control"
                   id='date-by-year'
                   v-on:change="date_change()">
            <input v-if="state_calendar==0"
                   type="month"
                   v-model='calendar_date'
                   id="date-by-year-month"
                   class="form-control"
                   v-on:change="date_change()">
        </div>

        <h3 class="font-weight-light" v-if='data_is_empty'>Операции за выбранную дату отсутствуют</h3>
        <canvas id="chart" height="100%" class="mt-3">

        </canvas>
    </div>
</div>
{% endblock content %}

budget/templates/budget/family.html
{% extends 'base.html' %}

{% block title %}Моя семья | {{block.super}}{% endblock title %}

{% block content %}
<div class="mb-3">

    {% include 'budget/include/family_tabs.html' %}

    <div class="mt-3">
    {% if family %}
        <div class="">
            <div class="">
                <h3 class="mb-0">{{family.name}}</h3>
            </div>
            <div class="">
                <p>Код для приглашения: <i>{{family.uuid}}</i></p>
            </div>
        </div>
        <hr>
        <h5 class="font-weight-light">Состав:</h5>
        <ul>
        {% for user in family.users.all %}
            {% if user == request.user %}
                <li class="li-none">Вы {% if user == family.author %} (администратор) {% endif %}</li>
            {% else %}
                <li class="li-none">
                    {% if user.first_name %}
                        {{user.first_name}} {{user.last_name}}
                    {% else %}
                        {{user}}
                    {% endif %}
                    {% if user == family.author %}
                        (администратор)
                    {% endif %}
                    {% if family.author == request.user %}
                    <a href="{% url 'b-family-delete-user' user.id %}" class="text-danger">
                        <span aria-hidden="true">&times;</span>
                    </a>
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
        </ul>

        <div class="d-flex justify-content-end">
            {% if request.user == family.author %}
                <a href="{% url 'b-family-delete' %}" class="ml-1 text-danger">Удалить</a>
            {% else %}
                <a href="{% url 'b-family-delete-user' request.user.id %}" class="">Покинуть</a>
            {% endif %}
        </div>
    {% else %}
        <h3 class="text-muted">Вы не состоите в семье</h3>
        <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Создать или вступить
        </a>
        <div class="collapse" id="collapseExample">
            <div class="card card-body">
              <form method="post" class="">
                  {% csrf_token %}
                  <div class="input-group input-group-sm">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Создать</span>
                      </div>
                      <input type="text" name="name" placeholder="Название" class="form-control form-control-sm w-50" required>
                      <div class="input-group-append ">
                          <input type="submit" class="btn btn-sm btn-outline-success">
                      </div>
                    </div>
              </form>
              <form method="post" class="mt-1">
                  {% csrf_token %}
                  <div class="input-group input-group-sm">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Вступить</span>
                      </div>
                      <input type="text" name="uuid" placeholder="Код для приглашения" class="form-control form-control-sm" required>
                      <div class="input-group-append">
                          <input type="submit" class="btn btn-sm btn-outline-success">
                      </div>
                    </div>
              </form>
            </div>
        </div>
    {% endif %}
    </div>
</div>
{% endblock content %}

budget/templates/budget/family_operation.html
{% extends 'base.html' %}

{% block title %}Моя семья | {{block.super}}{% endblock title %}

{% block content %}

<div class="mb-3">
    {% include 'budget/include/family_tabs.html' %}




    <div class="d-flex">
        <span class="display-4 {% if total > 0%}text-success{% elif total < 0%}text-danger{% endif %} my-3">{{total|floatformat:2}}</span>
    </div>

    <div class="d-flex">
        <div class="">
            <input
            type="month"
            value="{{year}}-{{month}}"
            class="form-control"
            onchange="month_change(this.value, '{{request.path}}')">
        </div>
    </div>

    {% if not operations %}
        <hr>
        <h3 class="font-weight-light">Операции за выбранный месяц отсутствуют</h3>
    {% endif %}

    {% for operation in operations %}
        {% ifchanged operation.date %}
            <h5 class="bg-info p-2 text-dark my-2">{{operation.date}}</h5>
        {% endifchanged %}
        {% include 'budget/include/cart_operation_family.html' %}
    {% endfor %}

</div>

{% endblock content %}

budget/templates/budget/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

budget/templates/budget/list_operation.html
{% extends 'base.html' %}

{% block title %}Мои финансы | {{block.super}}{% endblock title %}

{% block content %}

{% include 'budget/include/operation_tabs.html' %}
<div id="list-operation">
    <div id="app_category">
        <div class="d-flex">
            <span class="display-4 {% if total > 0%}text-success{% elif total < 0%}text-danger{% endif %} my-3">{{total|floatformat:2}}</span>
        </div>
        <div class="d-flex align-items-center">
            <div class="">
                <input
                type="month"
                value="{{month|date:'Y-m'}}"
                class="form-control"
                onchange="month_change(this.value, '{{request.path}}')">
            </div>
        </div>

        {% for operation in list_operation %}
        {% ifchanged operation.date %}
        <h5 class="bg-info p-2 text-dark my-2">{{operation.date}}</h5>
        {% endifchanged %}

        <div class="shadow-sm mt-2 bg-light div-hover border">
            <div class="container py-1">
                 <button type="button"
                         class="close"
                         data-dismiss="alert"
                         aria-label="Close"
                         v-on:click="delete_operation({{operation.id}}, '{% url 'b-operation-delete' operation.id %}')">
                     <span aria-hidden="true"><i class="bi bi-x-circle red-hover"></i></span>
                 </button>
                <a class="close mr-1" href="{% url 'b-operation-update' operation.id %}">
                     <span aria-hidden="true"><i class="bi bi-pencil"></i></span>
                </a>


                {% if operation.category.type_pay %}
                <h4 class="text-success">{{operation.value}}</h4>
                {% else %}
                <h4 class="text-danger">{{operation.value}}</h4>
                {% endif %}
                <p>{{operation.description|default:operation.category.name}}</p>
            </div>
        </div>
        {% empty %}
            <hr>
            <h3 class="font-weight-light">Операции за выбранный месяц отсутствуют</h3>
        {% endfor %}
    </div>
</div>


{% endblock content%}

budget/templates/budget/operation_create.html
{% extends 'base.html' %}


{% block content %}

{% if request.user.is_authenticated %}
<h3>{{request.user.username}}</h3>
{% else %}
<h3>Не авторизован</h3>
{% endif %}
<hr>


<div id="app_new_operation">
    <form method="post">
        {% csrf_token %}

        <div class="mb-1">{{form.value}}</div>
        <div class="mb-1">{{form.description}}</div>

        {% verbatim %}
        <div class="btn-group btn-group-toggle mb-1" data-toggle="buttons">
            <label class="btn btn-outline-success active">
                <input type="radio" value="0" name="type_pay" id="type_pay_0" v-model="state_radio"
                       v-on:change="radio_changed"> Расход
            </label>
            <label class="btn btn-outline-success">
                <input type="radio" value="1" name="type_pay" id="type_pay_1" v-model="state_radio"
                       v-on:change="radio_changed"> Доход
            </label>
        </div>

        <select name="category" id="id_category" class="custom-select">
            <template v-for="option in options">
                <option v-bind:value="option.id">{{option.name}}</option>
            </template>
        </select>
        {% endverbatim %}

        <input type="submit" class="btn btn-outline-success mt-2">

        {% for error in form.errors.values %}
            {{error}}
        {% endfor %}
    </form>
</div>



{% endblock content%}

budget/templates/budget/operation_update.html
{% extends 'base.html' %}


{% block content %}

{% if request.user.is_authenticated %}
<h3>{{request.user.username}}</h3>
{% else %}
<h3>Не авторизован</h3>
{% endif %}
<hr>


<div id="app_update_operation">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" value="{{form_data.type_pay}}" id="type_pay">
        <input type="hidden" value="{{form_data.instance}}" id="instance">

        <div class="mb-1">{{form.value}}</div>
        <div class="mb-1">{{form.description}}</div>

        {% verbatim %}
        <div class="btn-group btn-group-toggle mb-1" data-toggle="buttons">
            <label class="btn btn-outline-success active">
                <input type="radio" value="0" name="type_pay" id="type_pay_0" v-model="state_radio"
                       v-on:change="radio_changed"> Расход
            </label>
            <label class="btn btn-outline-success">
                <input type="radio" value="1" name="type_pay" id="type_pay_1" v-model="state_radio"
                       v-on:change="radio_changed"> Доход
            </label>
        </div>

        <select name="category" id="id_category" class="custom-select">
            <template v-for="option in options">
                <option v-if="option.id==instance" selected="selected" v-bind:value="option.id">{{option.name}}</option>
                <option v-else v-bind:value="option.id">{{option.name}}</option>
            </template>
        </select>
        {% endverbatim %}

        <input type="submit" class="btn btn-outline-success mt-2">

        {% for error in form.errors.values %}
            {{error}}
        {% endfor %}
    </form>
</div>
{% endblock content%}